services:
  storage-api:
    build:
      context: .
      dockerfile: src/Storage.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"

      Minio__Endpoint: "minio:9000"
      Minio__Region: "eu-central-1"
      Minio__AccessKey: "${MINIO_ROOT_USER}"
      Minio__SecretKey: "${MINIO_ROOT_PASSWORD}"
      Minio__UseSsl: "false"
      Minio__BucketName: "trackunit-images"
      Minio__PublicBaseUrl: "http://localhost:9000"

      InternalAuth__ApiKey: "${INTERNAL_AUTH_API_KEY}"
    depends_on:
      - minio
      - minio-init
  
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    
  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
        mc mb -p local/trackunit-images || true
      "

volumes:
  minio-data:
