<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Storage.Application\Storage.Application.csproj" />
    <ProjectReference Include="..\Storage.Domain\Storage.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ExternalServices\" />
    <Folder Include="Config\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="minio" Version="6.0.5" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
